Repository oemof/oemof-solph, pull requests merged in 2018-06, with the labels that each got.

#499 Add test to keep the API of dump/restore within a mayor release
  tests/test_scripts/test_solph/test_storage_investment/es_dump_test.oemof
  tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py
Labels: enhancement

#497 move not working console script to test
  nose.cfg
  oemof/tools/console_scripts.py
  setup.py
  tests/run_nose.py
  tests/test_console_scripts.py
Labels: bug

#494 Fixed #485
  oemof/outputlib/processing.py
  tests/constraint_tests.py
  tests/test_outputlib/test_views.py
  tests/test_processing.py
Labels: API, enhancement

#504 add existing flow-investment to capacity-flow constraint
  oemof/solph/components.py
  tests/constraint_tests.py
  tests/lp_files/connect_investment.lp
  tests/lp_files/investment_limit.lp
  tests/lp_files/storage.lp
  tests/lp_files/storage_invest_2.lp
  tests/lp_files/storage_invest_4.lp
  tests/lp_files/storage_invest_5.lp
  tests/lp_files/storage_invest_6.lp
  tests/test_components.py
  tests/test_scripts/test_solph/test_storage_investment/test_invest_storage_regression.py
Labels: bug

#501 Documentation/improve storage docs
  doc/oemof_solph.rst
  oemof/outputlib/processing.py
  oemof/solph/components.py
Labels: documentation

#481 Avoid error for flow objects without investment/nonconvex attribute
  oemof/solph/groupings.py
Labels: enhancement, oemof-solph
