Repository oemof/oemof-solph, pull requests merged in 2018-05, with the labels that each got.

#484 Add option for objective function timestep weighting indepent of con…
  oemof/solph/blocks.py
  oemof/solph/models.py
Labels: decision wanted, enhancement

#489 Features/solph existing investment
  doc/api/oemof.outputlib.rst
  doc/api/oemof.rst
  doc/api/oemof.solph.rst
  doc/api/oemof.tools.rst
  doc/oemof_solph.rst
  doc/whatsnew/v0-2-2.rst
  oemof/solph/blocks.py
  oemof/solph/components.py
  oemof/solph/options.py
  tests/constraint_tests.py
  tests/lp_files/fixed_source_invest_sink.lp
  tests/lp_files/transformer_invest_with_existing.lp
  tests/test_processing.py
  tests/test_scripts/test_solph/test_simple_model/input_data.csv
  tests/test_scripts/test_solph/test_simple_model/test_simple_dispatch.py
  tests/test_scripts/test_solph/test_simple_model/test_simple_invest.py
  tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py
Labels: enhancement, oemof-solph

#480 Decouple the investment of storage flows and capacity
  doc/whatsnew/v0-2-2.rst
  oemof/solph/components.py
Labels: enhancement

#492 Changes of documentation of ExtractionTurbineCHP
  doc/_files/ExtractionTurbine_range_of_operation.svg
  doc/oemof_solph.rst
  oemof/solph/components.py
Labels: documentation
