Repository oemof/oemof-solph, pull requests merged in 2019-11, with the labels that each got.

#644 Integrate lgtm
  README.rst
  oemof/network.py
  oemof/outputlib/processing.py
  oemof/solph/components.py
  oemof/solph/custom.py
  oemof/solph/groupings.py
  oemof/solph/network.py
  oemof/tools/console_scripts.py
  oemof/tools/logger.py
Labels: enhancement

#643 Remove unused datapackage fragments and update setup.py
  .coveragerc
  .travis.yml
  doc/api/oemof.tools.rst
  setup.py
Labels: bug, enhancement

#660 Copy entire SinkDSM code from #656
  doc/_files/Plot_delay_2013-01-01.svg
  doc/oemof_solph.rst
  doc/whatsnew/v0-3-2.rst
  oemof/solph/custom.py
  tests/constraint_tests.py
  tests/lp_files/dsm_module_delay.lp
  tests/lp_files/dsm_module_interval.lp
Labels: enhancement, oemof-solph
