Repository oemof/oemof-solph, pull requests merged in 2019-06, with the labels that each got.

#548 Update electrical components to work with Bus-Flow-Bus logic
  doc/whatsnew/v0-3-0.rst
  oemof/energy_system.py
  oemof/groupings.py
  oemof/solph/custom.py
  setup.py
  tests/basic_tests.py
  tests/regression_tests.py
  tests/test_scripts/test_solph/test_lopf/test_lopf.py
  tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py
Labels: enhancement

#593 Improve hints how to cite oemof
  README.rst
Labels: documentation

#601 Raise an AttributeError if deprecated attribute is used
  oemof/solph/components.py
  tests/test_components.py
Labels: bug, feedback wanted

#602 Generalise shared limits
  doc/whatsnew/v0-3-2.rst
  oemof/solph/constraints.py
  tests/constraint_tests.py
  tests/lp_files/emission_limit.lp
Labels: enhancement, oemof-solph
