Repository oemof/oemof-solph, pull requests merged in 2019-05, with the labels that each got.

#564 Fix/issue #563
  oemof/solph/blocks.py
Labels: bug, enhancement

#543 Improve annuity calculation in economics tool
  oemof/tools/economics.py
  tests/tool_tests.py
Labels: enhancement

#587 Improve documentation of Extraction Turine and GenericCHP
  doc/oemof_solph.rst
  oemof/solph/components.py
Labels: documentation

#589 Features/docu add math description caes
  doc/oemof_solph.rst
  oemof/solph/custom.py
Labels: documentation, feedback wanted
