Repository oemof/oemof-solph, pull requests merged in 2020-02, with the labels that each got.

#668 Features/add nonequidistant timeindex
  doc/whatsnew/v0-4-0.rst
  oemof/energy_system.py
  oemof/solph/components.py
  oemof/solph/models.py
  oemof/tools/helpers.py
  tests/test_models.py
Labels: API, enhancement

#677 Features/docs improve extraction turbine chp
  doc/_files/ExtractionTurbine_range_of_operation.svg
  doc/oemof_solph.rst
  doc/whatsnew/v0-3-3.rst
  oemof/solph/components.py
Labels: documentation

#679 Features/docs improve sequence data type
  doc/whatsnew/v0-4-0.rst
  oemof/network.py
  oemof/solph/components.py
  oemof/solph/custom.py
  oemof/solph/network.py
  oemof/solph/options.py
  oemof/solph/plumbing.py
Labels: enhancement
