Repository oemof/oemof-solph, pull requests merged in 2020-06, with the labels that each got.

#672 Features/shared limit
  docs/whatsnew/v0-4-0.rst
  src/oemof/solph/constraints.py
  tests/constraint_tests.py
  tests/lp_files/shared_limit.lp
Labels: enhancement

#705 Docs/improve documentation
  .github/PULL_REQUEST_TEMPLATE.md
  .prospector.yml
  AUTHORS.rst
  CONTRIBUTING.rst
  README.rst
  docs/changelog.rst
  docs/conf.py
  docs/getting_started.rst
  docs/index.rst
  docs/installation_and_setup.rst
  docs/old_usage.rst
  docs/reference/index.rst
  docs/results.rst
  docs/usage.rst
  docs/whatsnew/v0-0-1.rst
  docs/whatsnew/v0-0-2.rst
  docs/whatsnew/v0-0-3.rst
  docs/whatsnew/v0-0-4.rst
  docs/whatsnew/v0-0-5.rst
  docs/whatsnew/v0-0-6.rst
  docs/whatsnew/v0-0-7.rst
  docs/whatsnew/v0-1-0.rst
  docs/whatsnew/v0-1-1.rst
  docs/whatsnew/v0-1-2.rst
  docs/whatsnew/v0-1-4.rst
  docs/whatsnew/v0-2-0.rst
  docs/whatsnew/v0-2-1.rst
  docs/whatsnew/v0-2-2.rst
  docs/whatsnew/v0-2-3.rst
  docs/whatsnew/v0-3-0.rst
  docs/whatsnew/v0-3-1.rst
  docs/whatsnew/v0-3-2.rst
  docs/whatsnew/v0-3-3.rst
  docs/whatsnew/v0-4-0.rst
  setup.cfg
  setup.py
  src/oemof/solph/blocks.py
  src/oemof/solph/components.py
  src/oemof/solph/console_scripts.py
  src/oemof/solph/constraints.py
  src/oemof/solph/custom.py
  src/oemof/solph/groupings.py
  src/oemof/solph/helpers.py
  src/oemof/solph/models.py
  src/oemof/solph/network.py
  src/oemof/solph/options.py
  src/oemof/solph/plumbing.py
  src/oemof/solph/processing.py
  src/oemof/solph/views.py
  tests/test_processing.py
  tests/test_scripts/test_solph/test_invest_fix_flow/test_simple_invest_fixed.py
  tests/test_scripts/test_solph/test_simple_model/test_simple_dispatch.py
  tests/test_scripts/test_solph/test_simple_model/test_simple_invest.py
  tox.ini
Labels: documentation

#620 Feature/generic invest limit
  docs/usage.rst
  docs/whatsnew/v0-4-0.rst
  src/oemof/solph/constraints.py
  src/oemof/solph/options.py
  tests/constraint_tests.py
  tests/lp_files/generic_invest_limit.lp
Labels: enhancement

#710 Fix SolverStatus and '_bound' problem of pyomo 5.7.0
  docs/whatsnew/v0-4-1.rst
  setup.py
  src/oemof/solph/custom.py
  src/oemof/solph/models.py
Labels: bug
