Repository oemof/oemof-solph, pull requests merged in 2020-03, with the labels that each got.

#683 Make v0.3 development available in actual dev
  doc/_files/ExtractionTurbine_range_of_operation.svg
  doc/oemof_solph.rst
  doc/whats_new.rst
  doc/whatsnew/v0-4-0.rst
  oemof/outputlib/__init__.py
  oemof/solph/__init__.py
  oemof/solph/components.py
  oemof/tools/__init__.py
  setup.py
  tests/constraint_tests.py
  tests/lp_files/storage_fixed_losses.lp
  tests/lp_files/storage_invest_1_fixed_losses.lp
  tests/test_components.py
  tests/test_processing.py
Labels: help wanted

#663 Features/user warnings for debugging
  doc/api/oemof.tools.rst
  doc/oemof_solph.rst
  doc/oemof_tools.rst
  oemof/network.py
  oemof/outputlib/__init__.py
  oemof/solph/__init__.py
  oemof/solph/custom.py
  oemof/solph/network.py
  oemof/tools/__init__.py
  oemof/tools/debugging.py
  tests/test_components.py
  tests/test_scripts/test_solph/test_generic_caes/test_generic_caes.py
  tests/test_warnings.py
Labels: enhancement

#689 Fix docstring formulas
  doc/api/oemof.tools.rst
  oemof/tools/economics.py
Labels: bug

#636 Features/add non convex investment flow
  doc/_files/nonconvex_invest_investcosts_power.svg
  doc/_files/nonconvex_invest_specific_costs.svg
  doc/oemof_solph.rst
  doc/whatsnew/v0-4-0.rst
  oemof/solph/__init__.py
  oemof/solph/blocks.py
  oemof/solph/components.py
  oemof/solph/network.py
  oemof/solph/options.py
  tests/constraint_tests.py
  tests/lp_files/flow_invest_with_offset.lp
  tests/lp_files/flow_invest_with_offset_no_minimum.lp
  tests/lp_files/flow_invest_without_offset.lp
  tests/lp_files/storage_invest_all_nonconvex.lp
  tests/lp_files/storage_invest_with_offset.lp
  tests/lp_files/storage_invest_without_offset.lp
  tests/test_components.py
  tests/test_processing.py
Labels: enhancement, oemof-solph

#692 Add confirmed mac installation instructions
  doc/installation_and_setup.rst
Labels: documentation, enhancement
