Repository oemof/oemof-solph, pull requests merged in 2020-04, with the labels that each got.

#698 Fix sphinx tests on travis
  .travis.yml
  README.rst
  docs/_files/ExtractionTurbine_range_of_operation.svg
  docs/_files/GenericCHP.svg
  docs/_files/OffsetTransformer_efficiency.svg
  docs/_files/OffsetTransformer_power_relation.svg
  docs/_files/Plot_delay_2013-01-01.svg
  docs/_files/example_figures.png
  docs/_files/example_network.svg
  docs/_files/example_variable_chp.svg
  docs/_files/framework_concept.svg
  docs/_files/nonconvex_invest_investcosts_power.svg
  docs/_files/nonconvex_invest_specific_costs.svg
  docs/_files/oemof_solph_example.svg
  docs/_files/variable_chp_plot.svg
  docs/about_oemof.rst
  docs/conf.py
  docs/developing_oemof.rst
  docs/getting_started.rst
  docs/index.rst
  docs/installation.rst
  docs/installation_and_setup.rst
  docs/oemof_solph.rst
  docs/oemof_tools.rst
  docs/old_usage.rst
  docs/reference/index.rst
  docs/results.rst
  docs/usage.rst
  docs/whatsnew/v0-0-2.rst
  docs/whatsnew/v0-0-3.rst
  docs/whatsnew/v0-0-4.rst
  docs/whatsnew/v0-0-5.rst
  docs/whatsnew/v0-0-6.rst
  docs/whatsnew/v0-1-0.rst
  docs/whatsnew/v0-1-1.rst
  docs/whatsnew/v0-1-2.rst
  docs/whatsnew/v0-1-4.rst
  docs/whatsnew/v0-2-0.rst
  docs/whatsnew/v0-2-1.rst
  docs/whatsnew/v0-2-2.rst
  docs/whatsnew/v0-2-3.rst
  docs/whatsnew/v0-3-0.rst
  docs/whatsnew/v0-3-2.rst
  docs/whatsnew/v0-4-0.rst
  src/oemof/solph/components.py
  src/oemof/solph/network.py
  src/oemof/solph/views.py
  tox.ini
Labels: documentation, help wanted

#681 Features/rename storage capacity
  docs/conf.py
  docs/index.rst
  docs/usage.rst
  docs/whatsnew/v0-4-0.rst
  setup.cfg
  src/oemof/solph/components.py
  src/oemof/solph/models.py
  src/oemof/solph/views.py
  tests/lp_files/connect_investment.lp
  tests/lp_files/investment_limit.lp
  tests/lp_files/storage.lp
  tests/lp_files/storage_fixed_losses.lp
  tests/lp_files/storage_invest_1.lp
  tests/lp_files/storage_invest_1_fixed_losses.lp
  tests/lp_files/storage_invest_2.lp
  tests/lp_files/storage_invest_3.lp
  tests/lp_files/storage_invest_4.lp
  tests/lp_files/storage_invest_5.lp
  tests/lp_files/storage_invest_6.lp
  tests/lp_files/storage_invest_all_nonconvex.lp
  tests/lp_files/storage_invest_minimum.lp
  tests/lp_files/storage_invest_unbalanced.lp
  tests/lp_files/storage_invest_with_offset.lp
  tests/lp_files/storage_invest_without_offset.lp
  tests/lp_files/storage_unbalanced.lp
  tests/test_processing.py
  tests/test_scripts/test_solph/test_storage_investment/test_storage_with_tuple_label.py
Labels: API, oemof-solph

#623 Features/max active flow count
  docs/whatsnew/v0-4-0.rst
  src/oemof/solph/constraints.py
  src/oemof/solph/processing.py
  tests/constraint_tests.py
  tests/lp_files/flow_count_limit.lp
Labels: enhancement
