Repository oemof/oemof-solph, pull requests merged in 2023-08, with the labels that each got.

#895 Upgrade OffsetConverter
  examples/offset_converter_example/diesel_genset_data.csv
  examples/offset_converter_example/offset_diesel_genset_nonconvex_investment.py
  src/oemof/solph/components/_offset_converter.py
  tests/constraint_tests.py
  tests/lp_files/offset_converter.lp
  tests/lp_files/offsetconverter_nonconvex.lp
  tests/lp_files/offsetconverter_nonconvex_investment.lp
  tests/test_components.py
Labels: enhancement

#965 Define multi-period investment storage level for very first time step of optimization
  src/oemof/solph/components/_generic_storage.py
  tests/lp_files/connect_investment_multi_period.lp
  tests/lp_files/periodical_investment_limit.lp
  tests/lp_files/storage_invest_1_multi_period.lp
  tests/lp_files/storage_invest_2_multi_period.lp
  tests/lp_files/storage_invest_3_multi_period.lp
  tests/lp_files/storage_invest_4_multi_period.lp
  tests/lp_files/storage_invest_5_multi_period.lp
  tests/lp_files/storage_invest_6_multi_period.lp
  tests/lp_files/storage_invest_all_nonconvex_multi_period.lp
  tests/lp_files/storage_invest_minimum_multi_period.lp
  tests/lp_files/storage_invest_multi_period.lp
  tests/lp_files/storage_invest_with_offset_multi_period.lp
  tests/lp_files/storage_invest_without_offset_multi_period.lp
  tests/multi_period_constraint_tests.py
  tests/test_scripts/test_solph/test_multi_period_model/test_multi_period_investment_model.py
Labels: bug

#957 Make varying period lenghts possible
  docs/usage.rst
  docs/whatsnew/v0-5-1.rst
  examples/cellular/cellular.py
  examples/electrical/lopf.py
  examples/excel_reader/dispatch.py
  examples/invest_nonconvex_flow_examples/diesel_genset_nonconvex_investment.py
  examples/invest_nonconvex_flow_examples/house_with_nonconvex_investment.py
  examples/invest_nonconvex_flow_examples/house_without_nonconvex_investment.py
  examples/start_and_shutdown_costs/startup_shutdown.py
  examples/storage_investment/v1_invest_optimize_all_technologies.py
  examples/storage_investment/v2_invest_optimize_only_gas_and_storage.py
  examples/storage_investment/v3_invest_optimize_only_storage_with_fossil_share.py
  examples/storage_investment/v4_invest_optimize_all_technologies_with_fossil_share.py
  examples/storage_level_constraint/storage_level_constraint.py
  examples/time_index_example/non_equidistant_time_step_example.py
  src/oemof/solph/_energy_system.py
  src/oemof/solph/components/_generic_storage.py
  src/oemof/solph/components/experimental/_sink_dsm.py
  src/oemof/solph/flows/_flow.py
  src/oemof/solph/flows/_investment_flow_block.py
  tests/lp_files/multi_period_period_length.lp
  tests/multi_period_constraint_tests.py
Labels: bug, enhancement, help wanted

#962 Add storage_costs to GenericStorage
  examples/storage_costs/storage_costs.py
  src/oemof/solph/components/_generic_storage.py
  tests/constraint_tests.py
  tests/lp_files/storage.lp
Labels: enhancement
