Repository oemof/oemof-solph, pull requests merged in 2024-07, with the labels that each got.

#1088 Allow sinks/sources to have multiple inputs/outputs
  docs/whatsnew/v0-5-4.rst
  src/oemof/solph/components/_sink.py
  src/oemof/solph/components/_source.py
  tests/test_components/test_sink.py
  tests/test_components/test_source.py
  tests/test_warnings.py
Labels: enhancement, oemof-solph

#1090 Introduce variable for storage losses
  examples/storage_balanced_unbalanced/storage.py
  src/oemof/solph/components/_generic_storage.py
  tests/lp_files/nonequidistant_timeindex.lp
  tests/lp_files/shared_limit.lp
  tests/lp_files/shared_limit_multi_period.lp
  tests/lp_files/storage.lp
  tests/lp_files/storage_fixed_losses.lp
  tests/lp_files/storage_fixed_losses_multi_period.lp
  tests/lp_files/storage_invest_3.lp
  tests/lp_files/storage_invest_3_multi_period.lp
  tests/lp_files/storage_invest_5.lp
  tests/lp_files/storage_invest_5_multi_period.lp
  tests/lp_files/storage_level_constraint.lp
  tests/lp_files/storage_multi_period.lp
  tests/lp_files/storage_unbalanced.lp
  tests/lp_files/storage_unbalanced_multi_period.lp
  tests/test_components/test_storage.py
  tests/test_options.py
  tests/test_scripts/test_solph/test_storage_investment/test_storage_with_tuple_label.py
Labels: enhancement

#1089 Pandas warnings fixes
  src/oemof/solph/_plumbing.py
  src/oemof/solph/components/_offset_converter.py
  src/oemof/solph/components/_sink.py
  src/oemof/solph/components/_source.py
Labels: help wanted
